permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "LinuxClub BLOG"
email: "linuxclub.tut@gmail.com"
description: "東京工科大公認サークル LinuxClub のブログです."
github_username:  "lc-tut"
swiftype_searchId: ""
disqus_shortname: ""




url: "https://lc-tut.github.io"
imgrepo: "https://lc-tut.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"


# Added myself
gems: 
  - jekyll-paginate
